rules:
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  no-console: ["error"]
globals:
  Duktape: true
  NULL: true
  rpc: true
  ptr: true
  hexdump: true
  Backtracer: true
  send: true
  recv: true
  Frida: true
  Process: true
  Module: true
  ModuleMap: true
  Memory: true
  MemoryAccessMonitor: true
  Thread: true
  Int64: true
  UInt64: true
  NativePointer: true
  NativeFunction: true
  NativeCallback: true
  SystemFunction: true
  Socket: true
  SocketListener: true
  SocketConnection: true
  IOStream: true
  InputStream: true
  OutputStream: true
  UnixInputStream: true
  UnixOutputStream: true
  Win32InputStream: true
  Win32OutputStream: true
  File: true
  SqliteDatabase: true
  SqliteStatement: true
  Interceptor: true
  Stalker: true
  ApiResolver: true
  DebugSymbol: true
  Instruction: true
  ObjC: true
  Java: true
  WeakRef: true
  X86Writer: true
  X86Relocator: true
  ArmWriter: true
  ArmRelocator: true
  ThumbWriter: true
  ThumbRelocator: true
  Arm64Writer: true
  Arm64Relocator: true
  MipsWriter: true
  MipsRelocator: true